build:
  environment:
    php: '7.1'
  tests:
    override:
      -
        command: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml ./tests
        coverage:
          file: build/logs/clover.xml
          format: clover

filter:
    excluded_paths:
        - "src/Command"

checks:
    php:
        code_rating: true
        duplication: true
