build:
  environment:
    php: '7.1'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  tests:
    override:
      -
        command: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        coverage:
          file: build/logs/clover.xml
          format: clover
checks:
    php:
        code_rating: true
        duplication: true
